sudo: false
language: csharp 
services:
  - redis-server 
  
solution: ./redis-studies.sln
install:
    - nuget restore ./redis-studies.sln
    - bundle install
    - rake restore

script: 
  - rake test
