language: csharp

dotnet: 2.2.402
mono:
  - latest
os:
  - linux
services:
  - redis-server 
  
solution: ./redis-studies.sln
install:
    - dotnet restore ./redis-studies.sln

script: 
  - dotnet test ./Tests
branches:
  only: 
    - master