version: 1.0.{build}
configuration: Release
before_build:
  - nuget install redis-64 -excludeversion -source http://www.nuget.org/api/v2/
  - redis-64\redis-server.exe --service-install
  - redis-64\redis-server.exe --service-start
  - nuget restore redis-studies.sln
  - bundle install
  - rake restore
build:
  project: redis-studies.sln
  verbosity: minimal
  publish_nuget: false
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
